export const ONE_WEEK_IN_DAYS = 7;

export const ONE_DAY_IN_HOURS = 24;

export const ONE_HOUR_IN_MINUTE = 60;

export const ONE_MINUTE_IN_SECONDS = 60;

export const ONE_SECOND_IN_MS = 1000;

export const ONE_MINUTE_IN_MS = ONE_SECOND_IN_MS * ONE_MINUTE_IN_SECONDS;

export const ONE_HOUR_IN_MS = ONE_MINUTE_IN_MS * ONE_HOUR_IN_MINUTE;

export const ONE_DAY_IN_MS = ONE_HOUR_IN_MS * ONE_DAY_IN_HOURS;

export const ONE_WEEK_IN_MS = ONE_DAY_IN_MS * ONE_WEEK_IN_DAYS;
